name: maintenance_management_system
description: Maintenance task tracking app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  flutter: ^3.1.0-0 # Kept relatively close to master channel version
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #adaptive_breakpoints: ^0.1.1
  adaptive_navigation: ^0.0.3
  animations: ^2.0.2
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.3
  flutter_staggered_grid_view: ^0.6.1
  # google_fonts: ^3.0.1
  intl: ^0.19.0
  meta: ^1.7.0
  package_info_plus: ^8.3.1
  path_provider: ^2.0.11
  provider: ^6.0.2
  rally_assets: ^3.0.1
  scoped_model: ^2.0.0
  shared_preferences: ^2.0.15
  shrine_images: ^2.0.1
  url_launcher: ^6.2.4
  vector_math: ^2.1.2
  http: ^0.13.5
  jwt_decoder: ^2.0.1
  url_strategy: ^0.2.0
  openid_client: ^0.4.7
  path_to_regexp: ^0.4.0
  get: ^4.6.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  appflowy_board: ^0.1.2    
  google_generative_ai: ^0.2.0    
  pinput: ^5.0.0
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  args: ^2.3.1
  flutter_lints: ^2.0.1
  grinder: ^0.9.1
  path: ^1.8.1
  string_scanner: ^1.1.0
  test: ^1.21.1
  web_benchmarks: ^0.1.0

dependency_overrides:
  intl: ^0.18.0
  asn1lib: 1.5.8
  http: ^0.13.5

flutter:
  uses-material-design: true
  assets:
    - assets/config/dev.json
    - assets/config/prod.json
    - assets/config/dev-cloud.json
    - assets/config/stag.json
    - assets/images/
  generate: true
