# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - maintenance-webapp-production

on:
  push:
    branches:
      - maintenance-frontend-0.9.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.27.3"
      - run: flutter doctor -v

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "24.x"
      - run: npm install -g firebase-tools@11.0.1

      # Get dependencies and build Flutter web app
      - name: Get Flutter dependencies
        run: |
          cd campus/maintenance_frontend/frontend
          flutter clean
          flutter pub outdated
          flutter pub get

      - name: Build Flutter app
        run: |
          cd campus/maintenance_frontend/frontend
          flutter build web --release --dart-define=choreo_sts_client_id=${{ secrets.CHOREO_STS_CLIENT_ID }} --dart-define=asgardeo_client_id=${{ secrets.ASGARDEO_CLIENT_ID }} --dart-define=ENV=prod
          flutter config --enable-web

      - name: Upload Flutter build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build
          path: campus/maintenance_frontend/frontend/build/web

      - name: Move Flutter build contents to node-app artifact
        run: |
          cp -R campus/maintenance_frontend/frontend/build/web/* campus/maintenance_frontend/deployment/node-app/public-flutter

      - name: npm install, build, and test
        run: |
          cd campus/maintenance_frontend/deployment/node-app
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for node app
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: campus/maintenance_frontend/deployment/node-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "maintenancewebapp-production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_MAINTENANCE_WEB_APP }}
          package: .
